name: Build with SGDK

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download SGDK
      uses: i3h/download-release-asset@v1.3.3
      with:
        owner: Stephane-D
        repo: SGDK
        tag: v2.11 # Upgrade this on new version
        file: sgdk211.7z # Upgrade this on new version

    - name: Extract SGDK
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: sgdk211.7z # Upgrade this on new version
        pathTarget: sgdk
        
    - name: Run SGDK Build
      run: sgdk\bin\make -s -f sgdk\makefile.gen # Maybe use GDK_WIN here as well
      env:
        GDK_WIN: sgdk # This is set if needed in the Makefile

    - name: Upload the Rom
      uses: actions/upload-artifact@v4
      with:
        name: rom.bin
        path: out/rom.bin
        if-no-files-found: error

